import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from "next/link";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>

      <header className="bg-blue-600 text-white p-5">
          <div className="container mx-auto flex justify-between items-center">
              <Link href="/"  className="text-2xl font-bold">Paws Hub</Link>
              <nav>
                  <ul className="flex space-x-5">
                      <li><Link href="/" className="hover:underline">Inicio</Link></li>
                      <li><Link href="/about" className="hover:underline">Sobre Nosotros</Link></li>
                      <li><Link href="/contact" className="hover:underline">Contacto</Link></li>
                      <li><Link href="/screencast" className="hover:underline">Screencast</Link></li>
                      <li><Link href="/admin/posts" className="hover:underline">Admin</Link></li>
                  </ul>
              </nav>
          </div>
      </header>

      {children}

      <footer className="bg-blue-600 text-white p-5 mt-10">
          <div className="container mx-auto text-center">
              <p>&copy; 2023 Paws Hub. Todos los derechos reservados.</p>
          </div>
      </footer>

      </body>
    </html>
  )
}
